# Generated by Django 5.1.1 on 2024-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammate',
            name='phone',
            field=models.CharField(default='example@example.com', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammate',
            name='resume',
            field=models.TextField(),
        ),
    ]
